name: CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x # Using the current LTS version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build
